### PR TITLE
Mobile pop

### PR DESCRIPTION
**Pull request by ismailakinkunmi**
In mobile, When the user clicks (or taps) the hamburger button, the mobile menu appears, When the user clicks the close (X) button, the mobile menu disappears, When the user clicks any of the mobile menu options, the mobile menu disappears.

### CODE REVIEW

**Review by HENRYKC24 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUESTED:recycle:
Changes needed
## Hi @ismailakinkunmi:wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] I think that making some typographical errors might create a bad impression. Le's correct this line to be error-free.
image
"Hat tip :womans_hat: to **Microverse** for the opportunity, my coding **partners,** and code **reviewers** for their **contributions**."
what do you think?

- [ ] Don't you think including the link to your issue page would make it easier for other developers to collaborate? 
image
Please, add a link to the issue page here.

- [ ] I think it will be most appropriate to use "**star :star:**" here :point_down: 
image
That is what GitHub uses after all. Make sure to start the sentence with a capital letter.

- [ ] Your live link is broken. Please fix it. It would be frustrating to users when they follow a link that is broken. :point_down: 
image

- [ ] I want us to talk about your mobile design.
mobile
Comparing this design to the Figma template, I think you need to embrace pixel-perfection. Flowing the design make you a better developer and increases your chances of getting hired.
Figma Design:point_down:
image
**Please, implement the following**
- Make sure the app name (your name) uses the same font and color as specified in the Figma file. :arrow_down: 
image
- Make sure the margins and padding are the same as the Figma template. Your text is touching the left edge of the screen and there is unnecessary space to the right.
- [ ] The overlay(popup) mobile menu should cover the entire screen and have the background blurred. You should also stop the screen from scrolling to prevent weird behavior and also make sure to use the `z-index` CSS property to keep on top. Also, make sure that clicking any menu item takes the user to the exact portion of the page. The "Contact" option should take the user to the contact section, etc.
**Look at this for a better udesrtanding**:point_down:
Ismail
[OPTIONAL] I highly recommend that you use spaces to separate functions and some implementations in your JavaScript code to enhance readability. 
image
What do you think:thinking:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ismailakinkunmi** [comment]
find the link to project requirement below, all what you requesting for is
not in the project requirements
https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/7_mobile_menu.md

**Comment by ismailakinkunmi** [comment]
I went through the review five times, all are optional, no required and the
project wasn't approved moreso none of the feedback contribute to the
project requirements.

**Comment by HENRYKC24** [comment]
Hi @ismailakinkunmi, 
I understand you perfectly. I am sorry if this caused any inconveniences. One major requirement required of me in reviewing your code is to make sure that your design is almost identical with the chosen design on Figma.

I understand you have exerted a whole lot of effort building this project and I respect that.

Please, do your best to make sure your project follow the design and that you document it as professionally as possible.

If you need any assistance in any of the implementation of the design, please, reach out to any of us at Microverse. You may try reaching out to your peers first.

Thank you.

**Comment by HENRYKC24** [comment]
From the link you included above, I got this too.
Screenshot_20211221-153823
It says you MUST stick to the design as much as possible.

I know you can do this, @ismailakinkunmi. Good luck💪👍

**Pull request merged**
